services:
  proxy-server:
    build: .
    container_name: proxy_server_python
    ports:
      - "5000:5000"
    restart: always
    environment:
      - DISPLAY=:99
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge
    name: proxy_network