# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\x12\x05proxy\"H\n\x07Request\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07session\x18\x02 \x01(\t\x12\r\n\x05proxy\x18\x03 \x01(\x08\x12\x10\n\x08redirect\x18\x04 \x01(\x08\"\x1b\n\x08Response\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x1f\n\x0cProxyRequest\x12\x0f\n\x07session\x18\x01 \x01(\t\"@\n\rProxyResponse\x12\r\n\x05proxy\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x0e\n\x0cStatsRequest\"\xb7\x01\n\rStatsResponse\x12M\n\x16proxy_count_by_session\x18\x01 \x03(\x0b\x32-.proxy.StatsResponse.ProxyCountBySessionEntry\x12\x1b\n\x13total_valid_proxies\x18\x02 \x01(\x05\x1a:\n\x18ProxyCountBySessionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\xb8\x01\n\x0cProxyService\x12/\n\x0c\x46\x65tchContent\x12\x0e.proxy.Request\x1a\x0f.proxy.Response\x12;\n\x0eGetRandomProxy\x12\x13.proxy.ProxyRequest\x1a\x14.proxy.ProxyResponse\x12:\n\rGetProxyStats\x12\x13.proxy.StatsRequest\x1a\x14.proxy.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATSRESPONSE_PROXYCOUNTBYSESSIONENTRY']._loaded_options = None
  _globals['_STATSRESPONSE_PROXYCOUNTBYSESSIONENTRY']._serialized_options = b'8\001'
  _globals['_REQUEST']._serialized_start=22
  _globals['_REQUEST']._serialized_end=94
  _globals['_RESPONSE']._serialized_start=96
  _globals['_RESPONSE']._serialized_end=123
  _globals['_PROXYREQUEST']._serialized_start=125
  _globals['_PROXYREQUEST']._serialized_end=156
  _globals['_PROXYRESPONSE']._serialized_start=158
  _globals['_PROXYRESPONSE']._serialized_end=222
  _globals['_STATSREQUEST']._serialized_start=224
  _globals['_STATSREQUEST']._serialized_end=238
  _globals['_STATSRESPONSE']._serialized_start=241
  _globals['_STATSRESPONSE']._serialized_end=424
  _globals['_STATSRESPONSE_PROXYCOUNTBYSESSIONENTRY']._serialized_start=366
  _globals['_STATSRESPONSE_PROXYCOUNTBYSESSIONENTRY']._serialized_end=424
  _globals['_PROXYSERVICE']._serialized_start=427
  _globals['_PROXYSERVICE']._serialized_end=611
# @@protoc_insertion_point(module_scope)
