# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proxy_pb2 as proxy__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProxyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchContent = channel.unary_unary(
                '/proxy.ProxyService/FetchContent',
                request_serializer=proxy__pb2.Request.SerializeToString,
                response_deserializer=proxy__pb2.Response.FromString,
                _registered_method=True)
        self.GetRandomProxy = channel.unary_unary(
                '/proxy.ProxyService/GetRandomProxy',
                request_serializer=proxy__pb2.ProxyRequest.SerializeToString,
                response_deserializer=proxy__pb2.ProxyResponse.FromString,
                _registered_method=True)
        self.GetProxyStats = channel.unary_unary(
                '/proxy.ProxyService/GetProxyStats',
                request_serializer=proxy__pb2.StatsRequest.SerializeToString,
                response_deserializer=proxy__pb2.StatsResponse.FromString,
                _registered_method=True)


class ProxyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRandomProxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProxyStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchContent': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchContent,
                    request_deserializer=proxy__pb2.Request.FromString,
                    response_serializer=proxy__pb2.Response.SerializeToString,
            ),
            'GetRandomProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandomProxy,
                    request_deserializer=proxy__pb2.ProxyRequest.FromString,
                    response_serializer=proxy__pb2.ProxyResponse.SerializeToString,
            ),
            'GetProxyStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProxyStats,
                    request_deserializer=proxy__pb2.StatsRequest.FromString,
                    response_serializer=proxy__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proxy.ProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proxy.ProxyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProxyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxy.ProxyService/FetchContent',
            proxy__pb2.Request.SerializeToString,
            proxy__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRandomProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxy.ProxyService/GetRandomProxy',
            proxy__pb2.ProxyRequest.SerializeToString,
            proxy__pb2.ProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProxyStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxy.ProxyService/GetProxyStats',
            proxy__pb2.StatsRequest.SerializeToString,
            proxy__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
